# This is a Workflow name
name: Hello
# Runs on a trigger
on:
  workflow_dispatch:

# These are jobs inside Workflow
jobs:

#This is the name of the job
  greet:  # JOB NAME
    runs-on: ubuntu-latest  # GITHUB RUNNER
  
    steps:
      - name: say hello to users
        run: echo "HEY FOLKS! WELCOME ON-BOARD"
      - name: say hello to username
        run: echo "HELLO $USER"

  details: 
    runs-on: ubuntu-latest
    steps:
      - name: show what is the version of Python,Docker
        run: docker --version && python --version
